### ISSUE TITLE
加载性能较低

### ISSUE THREAD

**Issue by c4ys** [jonnywang/phpjieba#1]
未加载扩展PHP执行时间只需要0.2秒，加载后至少4s

**Comment by ixqbar** [comment]
这是因为加载时load了一次字典

**Comment by abelzhou** [comment]
这个如果写在php.ini的话  执行任何PHP指令的时候都需要加载  会影响效率的

**Comment by ixqbar** [comment]
@AbelZhou  请更新最新版本，使用ini_set控制

**Comment by ixqbar** [comment]
@c4ys 请参考另外解决方案 https://github.com/jonnywang/goredisjieba

**Comment by qinggan** [comment]
同上，加载后性能降太多了~用 so 控件就是冲着他的高性能来着的~

**Comment by ixqbar** [comment]
@qinggan 请参考另外解决方案 https://github.com/jonnywang/goredisjieba
