### ISSUE TITLE
creating a PHP package for projects

### ISSUE THREAD

**Issue by phillipswdc** [jonnywang/phpjieba#6]
Hello,

I have a server that is managed and does not allow us to install packages. Normally my sites would be located on something at AWS or some other VPS hosting. Is there anyway to get this converted into a PHP package that could be installed via composer on a local level? If so would would you please reach out to me so we can talk about this directly.

Thank you!

**Comment by ixqbar** [comment]
use https://github.com/jonnywang/goredisjieba
